# Generated by Django 3.2.9 on 2021-11-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docente_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['name'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
    ]
