# Generated by Django 3.2.9 on 2021-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_alter_docente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
