# Generated by Django 3.2.9 on 2021-11-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_alter_docente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='id',
            new_name='code',
        ),
    ]
