# Generated by Django 4.0 on 2021-12-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcurso',
            old_name='carrera',
            new_name='career',
        ),
        migrations.RemoveField(
            model_name='tcurso',
            name='grupo',
        ),
        migrations.AddField(
            model_name='tcurso',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tcarga_academica',
            name='creditos',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tcurso',
            name='credits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlSilabico.tcreadito'),
        ),
    ]
