# Generated by Django 4.0 on 2021-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0002_rename_carrera_tcurso_career_remove_tcurso_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcurso',
            name='group',
        ),
        migrations.AddField(
            model_name='tcurso',
            name='grupo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
