# Generated by Django 4.0 on 2021-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0003_remove_tcurso_group_tcurso_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcurso',
            name='career',
            field=models.CharField(max_length=200),
        ),
    ]
