# Generated by Django 4.0 on 2021-12-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0004_alter_tcurso_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdia',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
