# Generated by Django 4.0 on 2021-12-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0005_alter_tdia_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcreadito',
            options={'ordering': ['id'], 'verbose_name': 'tcredito', 'verbose_name_plural': 'tcreditos'},
        ),
        migrations.RemoveField(
            model_name='tcreadito',
            name='nro',
        ),
        migrations.AlterField(
            model_name='tcreadito',
            name='id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
