# Generated by Django 4.0 on 2021-12-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0007_alter_tdetalle_ca_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tdetalle_ca',
            table='tdetalle_carga',
        ),
    ]
