# Generated by Django 4.0 on 2021-12-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0008_alter_tdetalle_ca_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('idcarga', models.AutoField(db_column='idCarga', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catcurso',
            fields=[
                ('idcat_curso', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'catCurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catdocente',
            fields=[
                ('idcategoria', models.CharField(db_column='idCategoria', max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'catDocente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contenidosilabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=5)),
                ('capitulo', models.CharField(max_length=6)),
                ('tema', models.CharField(max_length=45)),
                ('nrohoras', models.CharField(db_column='nroHoras', max_length=2)),
            ],
            options={
                'db_table': 'contenidoSilabo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.CharField(db_column='idCurso', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=45)),
                ('grupo', models.CharField(max_length=1)),
                ('creditos', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursodetalle',
            fields=[
                ('idcursodetalle', models.AutoField(db_column='idCursoDetalle', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cursoDetalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('idd', models.CharField(db_column='idD', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('iddocente', models.CharField(db_column='idDocente', max_length=10, primary_key=True, serialize=False)),
                ('nombrecompleto', models.CharField(db_column='nombreCompleto', max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(db_column='idHorario', primary_key=True, serialize=False)),
                ('ht', models.IntegerField(db_column='hT')),
                ('hp', models.IntegerField(db_column='hP')),
                ('hrinicio', models.CharField(db_column='hrInicio', max_length=2)),
                ('hrfin', models.CharField(db_column='hrFin', max_length=2)),
                ('aula', models.CharField(blank=True, db_column='Aula', max_length=10, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registroavance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tema', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
            ],
            options={
                'db_table': 'registroAvance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocurso',
            fields=[
                ('idtipocurso', models.CharField(db_column='idtipoCurso', max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipoCurso',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='tcurso',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='tdetalle_ca',
            name='Id_Carga',
        ),
        migrations.RemoveField(
            model_name='tdetalle_ca',
            name='dia',
        ),
        migrations.DeleteModel(
            name='tcarga_academica',
        ),
        migrations.DeleteModel(
            name='tcreadito',
        ),
        migrations.DeleteModel(
            name='tcurso',
        ),
        migrations.DeleteModel(
            name='tdetalle_ca',
        ),
        migrations.DeleteModel(
            name='tdia',
        ),
        migrations.DeleteModel(
            name='tdocente',
        ),
    ]
