# Generated by Django 4.0 on 2021-12-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0009_carga_catcurso_catdocente_contenidosilabo_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catdocente',
            options={'managed': False, 'ordering': ['idcategoria']},
        ),
    ]
