# Generated by Django 4.0 on 2022-01-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0010_alter_catdocente_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contenidosilabo',
        ),
        migrations.DeleteModel(
            name='Registroavance',
        ),
        migrations.AlterModelOptions(
            name='catdocente',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='catcurso',
            table='catcurso',
        ),
        migrations.AlterModelTable(
            name='catdocente',
            table='catdocente',
        ),
        migrations.AlterModelTable(
            name='cursodetalle',
            table='cursodetalle',
        ),
        migrations.AlterModelTable(
            name='tipocurso',
            table='tipocurso',
        ),
    ]
