# Generated by Django 4.0 on 2022-01-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlSilabico', '0011_users_delete_contenidosilabo_delete_registroavance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('idsemestre', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'semestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('idsilabo', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=4)),
                ('capitulo', models.CharField(max_length=6)),
                ('sesion', models.IntegerField()),
            ],
            options={
                'db_table': 'silabo',
                'managed': False,
            },
        ),
    ]
