# Generated by Django 3.2.9 on 2021-11-25 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CursosHorarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
                ('ht', models.CharField(max_length=2)),
                ('hp', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('hrinit', models.CharField(max_length=2)),
                ('hr_i', models.CharField(max_length=2)),
                ('hr_f', models.CharField(max_length=2)),
                ('matriculados', models.CharField(max_length=2)),
                ('semestre', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=1)),
                ('id_cuso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
            options={
                'verbose_name': 'CursosHorarios',
                'verbose_name_plural': 'CursosHorarios',
                'ordering': ['day'],
            },
        ),
    ]
