# Generated by Django 3.2.9 on 2021-11-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cursoshorarios',
            name='group',
        ),
        migrations.AddField(
            model_name='curso',
            name='grupo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
