# Generated by Django 3.2.9 on 2021-11-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20211125_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursoshorarios',
            name='hrinit',
        ),
    ]
