# Generated by Django 3.2.9 on 2021-11-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_remove_cursoshorarios_hrinit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoshorarios',
            old_name='id_cuso',
            new_name='id_curso',
        ),
    ]
