# Generated by Django 3.2.9 on 2021-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_rename_id_cuso_cursoshorarios_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoshorarios',
            name='day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cursoshorarios',
            name='semestre',
            field=models.CharField(max_length=7),
        ),
    ]
