# Generated by Django 3.1.3 on 2021-11-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('Codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Carrera', models.CharField(max_length=50)),
                ('Docente', models.CharField(max_length=50)),
                ('Creditos', models.PositiveSmallIntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('Gpo', models.CharField(max_length=50)),
                ('Ht', models.CharField(max_length=50)),
                ('Hp', models.CharField(max_length=50)),
                ('Dia', models.CharField(max_length=50)),
                ('Horario', models.CharField(max_length=50)),
                ('Aula', models.CharField(max_length=50)),
                ('Matriculados', models.CharField(max_length=50)),
            ],
        ),
    ]
