# Generated by Django 3.2.9 on 2021-11-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carga_Academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargaacademica',
            old_name='Horario',
            new_name='Horario_F',
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='Horario_I',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
